# Generated by Django 4.1.5 on 2023-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_profilepic_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
