# Generated by Django 4.1.6 on 2023-02-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0029_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
