# Generated by Django 4.1.6 on 2023-02-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
