# Generated by Django 4.1.6 on 2023-02-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='customer',
        ),
    ]
