# Generated by Django 4.1.6 on 2023-02-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_service_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='profile_pic',
            new_name='profile',
        ),
    ]
