# Generated by Django 4.1.6 on 2023-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_service_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profile',
        ),
        migrations.AddField(
            model_name='service',
            name='more_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='mediafiles'),
        ),
    ]
