# Generated by Django 4.1.6 on 2023-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_remove_service_more_photo_service_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
