# Generated by Django 4.1.6 on 2023-02-25 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0055_alter_service_service_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="amount",
        ),
    ]
