# Generated by Django 4.1.6 on 2023-02-27 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0057_remove_profilepic_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="profile",
            new_name="more_photos",
        ),
    ]
