# Generated by Django 4.1.6 on 2023-02-27 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0058_rename_profile_service_more_photos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="more_photos",
            new_name="profile",
        ),
    ]
