# Generated by Django 4.1.6 on 2023-02-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0060_teamprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="team_profilepic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_profiles",
                to="store.teamprofile",
            ),
        ),
    ]
