# Generated by Django 4.1.6 on 2023-03-16 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0061_service_team_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="phone",
            field=models.IntegerField(
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
