# Generated by Django 4.1.6 on 2023-03-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0062_alter_enquiry_name_alter_enquiry_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("district", models.CharField(max_length=50)),
            ],
        ),
    ]
