# Generated by Django 4.1.6 on 2023-03-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0020_teamprofile"),
        ("store", "0064_alter_profilepic_account_alter_teamprofile_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="team_profilepic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_profiles",
                to="projectaccount.teamprofile",
            ),
        ),
        migrations.DeleteModel(
            name="TeamProfile",
        ),
    ]
