# Generated by Django 4.1.6 on 2023-02-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0016_account_more_photos_account_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='more_photos',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_pic',
        ),
    ]
