# Generated by Django 4.1.6 on 2023-03-28 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0066_teamprofile_alter_service_team_profilepic"),
        ("projectaccount", "0022_alter_teamprofile_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamProfile",
        ),
    ]
